import pathlib
p = pathlib.Path("E:/website/.opencode/skills/security-crypto/SKILL.md")
old = p.read_text(encoding="utf-8")

lines = []
lines.append("---")
lines.append("name: security-crypto")
lines.append("description: Comprehensive modern cryptography engineering skill")
lines.append("license: MIT")
lines.append("compatibility: opencode")
lines.append("metadata:")
lines.append("  audience: security-engineers")
lines.append("  domain: security")
lines.append("  paradigm: cryptographic")
lines.append("  integrates_with: [security-audit, backend-python, backend-go, backend-elixir, systems-embedded, infra-terraform]")
lines.append("---")
lines.append("")
lines.append("# Security Cryptography --- God-Tier Engineering Skill")
lines.append("")
lines.append("Comprehensive reference for modern cryptographic engineering")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 1. Cryptographic Foundations")
lines.append("")

pre = "\n".join(lines)
p.write_text(pre + "\n" + old, encoding="utf-8")
print("Fixed: " + str(len(pre) + len(old)) + " chars")
